# Generated by Django 5.0 on 2024-01-22 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lyamu', '0002_candidate_address_candidate_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='age',
            new_name='date_of_birth',
        ),
    ]
