# Generated by Django 5.0 on 2024-01-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lyamu', '0003_rename_age_candidate_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='date_of_birth',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
