# Generated by Django 5.0 on 2024-01-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lyamu', '0005_alter_candidate_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
